### ISSUE TITLE
Solo Barricades mode has a different tableau

### ISSUE THREAD

**Issue by doctor-g** [doctor-g/ThunderstoneQuestRandomizer#13]
[Over on BoardGameGeek](https://boardgamegeek.com/thread/2680331/article/37954659#37954659), it was pointed out that Barricades Solo mode uses a different tableau: 2 heroes and four marketplace items. This is specified in [the Barricades expansion rulebook, page 4](https://www.alderac.com/wp-content/uploads/2019/05/Barricades_Rulebook_small.pdf). The app should have a similar option, to use the smaller tableau when using Barricades Solo mode (or this should be the default in that case).

**Comment by renchap** [comment]
Some people prefer to play solo Barricades with the full tableau to get more choices, so this should be an option IMO
