### ISSUE TITLE
Randomize all possible wilderness tiles

### ISSUE THREAD

**Issue by doctor-g** [doctor-g/ThunderstoneQuestRandomizer#19]
Up through Quest 15, I think the options are:

- Giant Rat
- Ice Mosquito
- Grub
- Home Port

**Comment by mkol** [comment]
Note that Home Port can also have a LVL 0 monster.

A quote from the rulebook:

> When you take a Dungeon Phase in Home Port,
> you may battle 1 of your Boarding Parties, the
> level 0 Monster (i.e., Giant Rat), or the Guardian
> if it has been revealed. 

explicitly suggests existence of the monster in there.

While there is no monster printed on the tile (on non-Barricade side) - there is nothing in the rules that says that there should be no LVL 0 monster. Note that the early version of The Wilderness didn't have the rat printed either.

**Comment by doctor-g** [comment]
Ah, of course you are right. I was not thinking clearly this morning when I wrote up and then "solved" this issue.

When not in Barricades mode, my group always just uses whatever Level 0 monster is on the back of the Guardian. I believe this is the regular way to play. In this mode, then, it seems the only distinction would be between the Home Port and any other Wilderness.

In Barricades mode, the Level 0 monster is determined instead by the Wilderness tile itself, which will have either Giant Rat, Ice Mosquitoes, or Grubs. 

It seems the issue of "wilderness randomization" then requires considering Barricades Mode vs competitive mode first. Does that sound right?

**Comment by mkol** [comment]
I believe LVL 0 monster is not bound to the guardian used for the game.

From Barricade Rulebook:

> In
> any mode of Thunderstone Quest,
> you may play with a Monster
> printed on the Wilderness tile, or
> you may use any Monster from
> the back of any Guardian.

**Comment by doctor-g** [comment]
Ah, OK, so the core issue then is that Level 0 monster and Wilderness are independent. One can use the Level 0 Monster from any available Quest at any time, whether it's from a Wilderness tile or the back of a Guardian. Whether or not someone uses the Home Port & Voyage is separate from that. 

The current implementation then could be changed so that it gives one of Giant Rat, Ice Mosquitoes, or Grubs. This would be randomizing the _Level 0 Monster_, not _the Wilderness_. A separate item could be added that randomizes the wilderness, which at this point would just be a percent chance of having the Home Port & Voyage rules. Doing the first part of this is easy and doesn't change the code materially. Doing the second requires adding a new setting. I wonder if there is value in having the app suggest that, some 25% of the time or so, Home Port & Voyages are used, vs. just leaving that up to the discretion of the players.

Another approach would be to combine these, to have an entry like "Randomize Level 0 Monster and Wilderness," with responses of the form "[Level 0 Monster] in [Location]," for example, "Grub in the Wilderness" or "Giant Rat in the Home Port".
